spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.36.75:3306/share_books?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1092982300

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_catalog: share_books
        default_schema: share_books

server:
  port: 8081


# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "